/// 2022 Systopia Lab, Computer Science, University of British Columbia. All rights reserved.


// OSSPEC Definitions for `MyOs`

// THIS FILE IS AUTOGENERATED BY THE VELOSIRAPTOR COMPILER



#ifndef MYOS_OSSPEC_H_
#define MYOS_OSSPEC_H_ 1

#include <barrelfish/barrelfish.h>
#include <velosiraptor/types.h>

#define MyErrval errval_t


struct capref;

// #define capref MyCapref;

typedef struct capref MyCapref;

struct MyVNode {
    MyCapref cap;
    MyCapref mapping;
};

typedef struct MyVNode MyVNode;

struct MyFrame {
    MyCapref cap;
    MyCapref mapping;
};

typedef struct MyFrame MyFrame;

#define FRAME_DEFAULT ((MyFrame) { 0 })

extern vaddr_t os_virt_alloc(size_t sz);

extern void os_virt_free(vaddr_t va, size_t sz);

extern MyVNode os_vnode_alloc(UnitType ty);

extern void os_vnode_free(MyVNode vnode);

extern bool vnode_is_valid(MyVNode vnode);

extern paddr_t frame_to_paddr(MyFrame pa);

extern MyCapref get_vnode_for_va(vaddr_t va);

extern MyCapref get_mapping_for_va(vaddr_t va);

extern bool errval_to_bool(MyErrval err);

extern MyErrval my_vnode_map(MyCapref dest, MyCapref src, vaddr_t va, flags_t attr, genaddr_t off, size_t sz, MyCapref mapping);

extern MyErrval my_vnode_unmap(MyCapref table, MyCapref mapping);

extern MyErrval my_vnode_modify_flags(MyCapref table, vaddr_t va, size_t sz, flags_t attr);

#endif // MYOS_OSSPEC_H_
