/// 2022 Systopia Lab, Computer Science, University of British Columbia. All rights reserved.


// OSSPEC Definitions for `MyOs`

// THIS FILE IS AUTOGENERATED BY THE VELOSIRAPTOR COMPILER



#ifndef MYOS_OSSPEC_H_
#define MYOS_OSSPEC_H_ 1


#include "types.h"

#endif // MYOS_OSSPEC_H_
